"""Emit the graph diagram as Mermaid.

    python -m scripts.draw_graph            # print to stdout
    python -m scripts.draw_graph --write    # update docs/architecture.md

The diagram is generated from the compiled graph, so it cannot drift from
what actually runs. A hand-drawn architecture diagram is out of date the
moment someone adds an edge; this one is out of date only if nobody runs
the command, which is why `--write` exists.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from app.config import PROJECT_ROOT
from app.graph.build import get_graph

DOCS = PROJECT_ROOT / "docs"
TARGET = DOCS / "architecture.md"

HEADER = """# Architecture

Generated by `python -m scripts.draw_graph --write`. Do not edit by hand.

## Request flow

```mermaid
"""

FOOTER = """```

## Nodes

| Node | Responsibility |
| --- | --- |
| `router` | Classifies intent. Keyword fast-path for pleasantries, small LLM otherwise. Sets `intent`, `secondary_intent`, `confidence`. |
| `inquiry` | Answers from retrieved documents, or refuses. Never answers from model knowledge. |
| `booking` | Extracts appointment details, checks availability, writes to the calendar. |
| `complaint` | Assesses severity, logs the complaint, escalates by rule. |
| `other` | Greetings, thanks, and messages outside the clinic's scope. |
| `finalise` | Appends any secondary-intent note and assembles the turn record for analytics. |

Every path converges on `finalise`, so logging happens in one place
rather than at five call sites.
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="Write docs/architecture.md.")
    args = parser.parse_args()

    try:
        mermaid = get_graph().get_graph().draw_mermaid()
    except Exception as exc:
        print(f"Could not render the graph: {type(exc).__name__}: {exc}")
        return 1

    if not args.write:
        print(mermaid)
        return 0

    DOCS.mkdir(exist_ok=True)
    TARGET.write_text(HEADER + mermaid + FOOTER, encoding="utf-8")
    print(f"Wrote {TARGET.relative_to(PROJECT_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
